name = "vote4photo"

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2023-12-01"

[vars]
ALLOW_REGISTER = true
SECRET = "dev-mode"
AUTH_KEY_SECRET = '73q*********'
BUCKET_NAME = 'photos-dev'
CHAIN_ID = '0x7a69'
#Sepolia: CHAIN_ID = 'aa36a7'
V4P_ACCOUNT = '0x1a***********'
V4P_ACCOUNT_PRIV_KEY = '0x01**********'
V4P_CONTRACT = '0x24*******'
V4P_FORWARDER = '0x32*******'
MONEY_PER_VOTE = 0.15

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "v4p-db"
database_id = "******"
preview_database_id = "DB" # Required for Pages local development

[[r2_buckets]]
binding = 'PHOTO_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'photos-dev'

[triggers]
# Schedule cron triggers:
# - At every minute
crons = [ "* * * * *" ]